### ISSUE TITLE
Downloads start on "paused"

### ISSUE THREAD

**Issue by infinicode** [isc30/eMulerr#6]
Hello,

First of all, thanks for this great addon!

When adding a new download, the ed2k file starts in state "Paused". You need to enter amule's ui to change the status to "Downloading". The download client is configured with "Start" in the "Initial State" configuration option, so it should start automatically.

**Comment by isc30** [comment]
Hi, you are right, in some cases the downloads get paused. I don't really know why this is, but i think it can be easily fixed by sending the "resume" command every 30s or something like that.

I have also found that in these cases, the downloads start automatically later on.

Marking this issue as "Good First Issue" in case someone wants to pick it up. The solution implementation could be:
- Add a new job that runs every 30s
- Iterate over all downloads, send the "resume" command to amule

**Comment by MrOrange9-JCT** [comment]
+1 on this issue. I think this usually happens when downloads stay as stalled for a long time, and amule automatically pauses them (could be wrong).

**Comment by isc30** [comment]
Starting work on this one

**Comment by isc30** [comment]
Done :)
